### ISSUE TITLE
Local build broken libatk-1.0.so

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-aria-practices#61]
Trying to local build I get the following error.  looks like an unmet dep on `libatk-1.0.so.` I'm using WSL Ubuntu on Windows so that is possible.

Also I have respec installed but you script does a very simple test for existence, not a version and I probably have an old version.

```
$ ./scripts/build.sh
/home/wsl/.nvm/versions/node/v16.14.2/bin/respec
[FATAL] Error: Failed to launch the browser process!
/home/wsl/.nvm/versions/node/v16.14.2/lib/node_modules/respec/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/wsl/.nvm/versions/node/v16.14.2/lib/node_modules/respec/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/home/wsl/.nvm/versions/node/v16.14.2/lib/node_modules/respec/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:538:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The suggested https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md is no help at all

**Comment by SteveALee** [comment]
To answer my own problem - the issue was NOT WSL specific just missing all the Debian deps listed in the troubleshooting file

Answer was 

``` bash
sudo apt install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```

I still get errors but assume I can ignorethose?

``` bash
/home/wsl/.nvm/versions/node/v16.14.2/bin/respec
[ERROR] data-include failed: common/acknowledgements/funders.html (Failed to fetch).
[ERROR] data-include failed: common/acknowledgements/funders.html (Failed to fetch).
   Count: 1
  Plugin: core/data-include
[WARNING] Missing localization strings for en-US.
```

**Comment by richnoah** [comment]
@SteveALee nice troubleshooting.  Yes, those errors can be ignored.  They are expected at this point.
